title: My Github blog
author: Andrés  
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Mi blog sobre mi aprendizaje en github
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
